---
- name: Deploy and Restart Web Container
  hosts: remote_web_servers
  become: yes
  become_user: root
  tasks:
    - name: Check if Tomcat directory exists
      stat:
        path: /opt/tomcat
      register: tomcat_dir

    - name: Download and Install Tomcat
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.13/bin/apache-tomcat-10.1.13.tar.gz
        dest: /opt/
        remote_src: yes
      when: tomcat_dir.stat.exists == False
      
    - name: Rename Tomcat directory
      command: mv /opt/apache-tomcat-10.1.13 /opt/tomcat
      when: tomcat_dir.stat.exists == False
      
    - name: Copy .war file to the remote server
      copy:
        src: /home/labsuser/PG-DO_Configuration-Management-with-Ansible-and-Terraform/CEP-1/Deploy/target/simplilearn-pgdo-course2-cep1.war
        dest: /opt/tomcat/webapps/

    - name: Stop Tomcat
      command: /opt/tomcat/bin/shutdown.sh
      async: 60 
      poll: 0
      ignore_errors: yes
      register: shutdown_job

    - name: Wait for Tomcat to stop
      async_status:
        jid: "{{ shutdown_job.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 10
      delay: 5

    - name: Start Tomcat using nohup
      shell: "nohup /opt/tomcat/bin/startup.sh &"
