---
- name: Run Maven Build via Ansible
  hosts: master
  become: yes
  vars:
    git_repo_url: https://github.com/Lakan-Ilaw/PG_DO_Course2_CEP1.git
    project_directory: /home/labsuser/PG-DO_Configuration-Management-with-Ansible-and-Terraform/CEP-1/Deploy/
    
  tasks:
    - name: Verify Maven Installation
      apt:
        name: maven
        update_cache: true
        
    - name: Check if the project directory exists
      stat:
        path: "{{ project_directory }}"
      register: project_dir
      
    - name: Zip the project directory with a timestamp and delete the original directory
      command: |
        zip -r "/tmp/project_{{ ansible_date_time.epoch }}.zip" "{{ project_directory }}" &&
        rm -rf "{{ project_directory }}"
      when: project_dir.stat.exists


    - name: Clone the Git repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ project_directory }}"

    - name: Run Maven Goals
      command: mvn "{{ item }}"
      args:
        chdir: "{{ project_directory }}"
      loop:
        - test
        - pmd:pmd
        - verify
        - clean
        - install
      register: maven_result
        
    - name: Display Error Message
      debug:
        msg: "An error has been found on {{ item.item }} step."
      loop: "{{ maven_result.results }}"
      loop_control:
        loop_var: item
      when: item.rc != 0
